/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym_comment = 2,
  sym_atom = 3,
  sym_license_expand = 4,
  sym_license_group = 5,
  sym_license_neg = 6,
  sym_star = 7,
  sym_license = 8,
  sym_file = 9,
  sym_entry = 10,
  sym_license_spec = 11,
  aux_sym_file_repeat1 = 12,
  aux_sym_entry_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [sym_atom] = "atom",
  [sym_license_expand] = "license_expand",
  [sym_license_group] = "license_group",
  [sym_license_neg] = "license_neg",
  [sym_star] = "star",
  [sym_license] = "license",
  [sym_file] = "file",
  [sym_entry] = "entry",
  [sym_license_spec] = "license_spec",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym_entry_repeat1] = "entry_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [sym_atom] = sym_atom,
  [sym_license_expand] = sym_license_expand,
  [sym_license_group] = sym_license_group,
  [sym_license_neg] = sym_license_neg,
  [sym_star] = sym_star,
  [sym_license] = sym_license,
  [sym_file] = sym_file,
  [sym_entry] = sym_entry,
  [sym_license_spec] = sym_license_spec,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym_entry_repeat1] = aux_sym_entry_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_license_expand] = {
    .visible = true,
    .named = true,
  },
  [sym_license_group] = {
    .visible = true,
    .named = true,
  },
  [sym_license_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_license] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_license_spec] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '@') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '-' || '9' < lookahead)) ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(9);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_license_expand);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_license_group);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_license_neg);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_license_neg);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_star);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_license);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '@') ADVANCE(1);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_license);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '.') ADVANCE(17);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_license);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_license_expand] = ACTIONS(1),
    [sym_license_group] = ACTIONS(1),
    [sym_license_neg] = ACTIONS(1),
    [sym_star] = ACTIONS(1),
    [sym_license] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_file] = STATE(8),
    [sym_entry] = STATE(6),
    [aux_sym_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [sym_atom] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_license_spec] = STATE(3),
    [aux_sym_entry_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(9),
    [sym_comment] = ACTIONS(9),
    [sym_atom] = ACTIONS(11),
    [sym_license_expand] = ACTIONS(13),
    [sym_license_group] = ACTIONS(13),
    [sym_license_neg] = ACTIONS(15),
    [sym_star] = ACTIONS(13),
    [sym_license] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_license_spec] = STATE(4),
    [aux_sym_entry_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_blank_line] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
    [sym_atom] = ACTIONS(19),
    [sym_license_expand] = ACTIONS(13),
    [sym_license_group] = ACTIONS(13),
    [sym_license_neg] = ACTIONS(15),
    [sym_star] = ACTIONS(13),
    [sym_license] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym_license_spec] = STATE(4),
    [aux_sym_entry_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_blank_line] = ACTIONS(21),
    [sym_comment] = ACTIONS(21),
    [sym_atom] = ACTIONS(23),
    [sym_license_expand] = ACTIONS(25),
    [sym_license_group] = ACTIONS(25),
    [sym_license_neg] = ACTIONS(28),
    [sym_star] = ACTIONS(25),
    [sym_license] = ACTIONS(28),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_blank_line] = ACTIONS(31),
    [sym_comment] = ACTIONS(31),
    [sym_atom] = ACTIONS(33),
    [sym_license_expand] = ACTIONS(31),
    [sym_license_group] = ACTIONS(31),
    [sym_license_neg] = ACTIONS(33),
    [sym_star] = ACTIONS(31),
    [sym_license] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      sym_atom,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 2,
      sym_blank_line,
      sym_comment,
    STATE(7), 2,
      sym_entry,
      aux_sym_file_repeat1,
  [15] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      sym_atom,
    ACTIONS(41), 2,
      sym_blank_line,
      sym_comment,
    STATE(7), 2,
      sym_entry,
      aux_sym_file_repeat1,
  [30] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 15,
  [SMALL_STATE(8)] = 30,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_license_spec, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_license_spec, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gentoo_package_license(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gentoo_package_license",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
