/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym_comment = 2,
  aux_sym_entry_token1 = 3,
  aux_sym_entry_token2 = 4,
  anon_sym_LF = 5,
  sym_category = 6,
  sym_http_url = 7,
  sym_https_url = 8,
  sym_ftp_url = 9,
  sym_generic_url = 10,
  sym_file = 11,
  sym_entry = 12,
  sym_url = 13,
  aux_sym_file_repeat1 = 14,
  aux_sym_entry_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [aux_sym_entry_token1] = "entry_token1",
  [aux_sym_entry_token2] = "entry_token2",
  [anon_sym_LF] = "\n",
  [sym_category] = "category",
  [sym_http_url] = "http_url",
  [sym_https_url] = "https_url",
  [sym_ftp_url] = "ftp_url",
  [sym_generic_url] = "generic_url",
  [sym_file] = "file",
  [sym_entry] = "entry",
  [sym_url] = "url",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym_entry_repeat1] = "entry_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [aux_sym_entry_token1] = aux_sym_entry_token1,
  [aux_sym_entry_token2] = aux_sym_entry_token2,
  [anon_sym_LF] = anon_sym_LF,
  [sym_category] = sym_category,
  [sym_http_url] = sym_http_url,
  [sym_https_url] = sym_https_url,
  [sym_ftp_url] = sym_ftp_url,
  [sym_generic_url] = sym_generic_url,
  [sym_file] = sym_file,
  [sym_entry] = sym_entry,
  [sym_url] = sym_url,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym_entry_repeat1] = aux_sym_entry_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_entry_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entry_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_category] = {
    .visible = true,
    .named = true,
  },
  [sym_http_url] = {
    .visible = true,
    .named = true,
  },
  [sym_https_url] = {
    .visible = true,
    .named = true,
  },
  [sym_ftp_url] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_url] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_entry_token2);
      if (eof) ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(15);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == 's') ADVANCE(17);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'h') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 23:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_entry_token1);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_entry_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_category);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_http_url);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_https_url);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ftp_url);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_generic_url);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_entry_token1] = ACTIONS(1),
    [aux_sym_entry_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_file] = STATE(17),
    [sym_entry] = STATE(2),
    [aux_sym_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [aux_sym_entry_token1] = ACTIONS(7),
    [sym_category] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      aux_sym_entry_token1,
    ACTIONS(9), 1,
      sym_category,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      sym_blank_line,
      sym_comment,
    STATE(3), 2,
      sym_entry,
      aux_sym_file_repeat1,
  [18] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(20), 1,
      aux_sym_entry_token1,
    ACTIONS(23), 1,
      sym_category,
    ACTIONS(17), 2,
      sym_blank_line,
      sym_comment,
    STATE(3), 2,
      sym_entry,
      aux_sym_file_repeat1,
  [36] = 3,
    ACTIONS(30), 1,
      anon_sym_LF,
    ACTIONS(28), 2,
      sym_blank_line,
      aux_sym_entry_token1,
    ACTIONS(26), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_category,
  [49] = 3,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(34), 2,
      sym_blank_line,
      aux_sym_entry_token1,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_category,
  [62] = 3,
    ACTIONS(40), 1,
      sym_generic_url,
    STATE(15), 1,
      sym_url,
    ACTIONS(38), 3,
      sym_http_url,
      sym_https_url,
      sym_ftp_url,
  [74] = 2,
    ACTIONS(34), 1,
      aux_sym_entry_token1,
    ACTIONS(32), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      sym_comment,
      sym_category,
  [84] = 2,
    ACTIONS(44), 1,
      aux_sym_entry_token1,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      sym_comment,
      sym_category,
  [94] = 3,
    ACTIONS(46), 1,
      aux_sym_entry_token1,
    ACTIONS(48), 1,
      aux_sym_entry_token2,
    STATE(11), 1,
      aux_sym_entry_repeat1,
  [104] = 3,
    ACTIONS(46), 1,
      aux_sym_entry_token1,
    ACTIONS(50), 1,
      aux_sym_entry_token2,
    STATE(11), 1,
      aux_sym_entry_repeat1,
  [114] = 3,
    ACTIONS(52), 1,
      aux_sym_entry_token1,
    ACTIONS(55), 1,
      aux_sym_entry_token2,
    STATE(11), 1,
      aux_sym_entry_repeat1,
  [124] = 2,
    ACTIONS(46), 1,
      aux_sym_entry_token1,
    STATE(9), 1,
      aux_sym_entry_repeat1,
  [131] = 2,
    ACTIONS(46), 1,
      aux_sym_entry_token1,
    STATE(10), 1,
      aux_sym_entry_repeat1,
  [138] = 2,
    ACTIONS(57), 1,
      aux_sym_entry_token1,
    ACTIONS(59), 1,
      aux_sym_entry_token2,
  [145] = 2,
    ACTIONS(55), 1,
      aux_sym_entry_token2,
    ACTIONS(61), 1,
      aux_sym_entry_token1,
  [152] = 1,
    ACTIONS(63), 1,
      sym_category,
  [156] = 1,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 62,
  [SMALL_STATE(7)] = 74,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 104,
  [SMALL_STATE(11)] = 114,
  [SMALL_STATE(12)] = 124,
  [SMALL_STATE(13)] = 131,
  [SMALL_STATE(14)] = 138,
  [SMALL_STATE(15)] = 145,
  [SMALL_STATE(16)] = 152,
  [SMALL_STATE(17)] = 156,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 3, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 4, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 5, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 5, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_url, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gentoo_mirrors(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gentoo_mirrors",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
